apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes-api
  template:
    metadata:
      labels:
        app: mes-api
    spec:
      containers:
      - name: fastapi
        image: python:3.9-slim
        command: ["sh", "-c", "pip install fastapi uvicorn psycopg2-binary && python /app/app.py"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: code
          mountPath: /app/app.py
          subPath: app.py
      volumes:
      - name: code
        configMap:
          name: backend-code
---
apiVersion: v1
kind: Service
metadata:
  name: mes-api-service
spec:
  type: NodePort
  selector:
    app: mes-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30461
