apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes-frontend
  template:
    metadata:
      labels:
        app: mes-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: frontend-build
---
apiVersion: v1
kind: Service
metadata:
  name: mes-frontend-service
spec:
  type: NodePort
  selector:
    app: mes-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30173
