apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes-api
  template:
    metadata:
      labels:
        app: mes-api
    spec:
      containers:
        - name: mes-api
          image: python:3.9-slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /app/api_modules &&
              cp /mnt/*.py /app/api_modules/ &&
              mv /app/api_modules/app.py /app/app.py &&
              touch /app/api_modules/__init__.py &&
              pip install --no-cache-dir fastapi uvicorn psycopg2-binary kubernetes pydantic psutil &&
              python /app/app.py
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
            - name: CORS_ORIGINS
              value: "__CORS_ORIGINS__"
          volumeMounts:
            - name: code-volume
              mountPath: /mnt
      volumes:
        - name: code-volume
          configMap:
            name: api-code
---
apiVersion: v1
kind: Service
metadata:
  name: mes-api-service
spec:
  type: NodePort
  selector:
    app: mes-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30461
